services:
  node:
    build: .
    environment:
      - NODE_ENV=development
    command: >
      bash -c "npm ci &&
               npm run dev"
    volumes:
      - ./:/app
    ports:
      - "5173:5173"
    tty: true
